### ISSUE TITLE
Vec

### ISSUE THREAD

**Issue by markKL1** [thunderseethe/parallel_array_init#1]
I like the library, thanks!

Is there any way to use it with `Vec`?

**Comment by thunderseethe** [comment]
This library doesn't interface with Vec. However it's depdendency `rayon` offers a lot of utility for working with Vec.

In this instance [rayon can construct a Vector from a parallel iterator](https://docs.rs/rayon/1.3.0/rayon/iter/trait.FromParallelIterator.html). This can be used to initialize a Vec
